# TCL File Generated by Component Editor 13.1
# Wed Nov 19 23:19:19 CST 2014
# DO NOT MODIFY


# 
# cdc_fifo "cdc_fifo" v1.0
# tpu 2014.11.19.23:19:18
# Saturn CDC FIFO
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module cdc_fifo
# 
set_module_property DESCRIPTION "Saturn CDC FIFO"
set_module_property NAME cdc_fifo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Bridges and Adapters/DMA"
set_module_property AUTHOR tpu
set_module_property DISPLAY_NAME cdc_fifo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cdc_fifo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file cdc_fifo.v VERILOG PATH cdc_fifo.v TOP_LEVEL_FILE
add_fileset_file fifo4k.qip OTHER PATH fifo4k.qip
add_fileset_file fifo4k.v VERILOG PATH fifo4k.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end reg_fifo_ctrl reg_fifo_ctrl Input 16
add_interface_port conduit_end reg_blk_addr reg_blk_addr Input 32
add_interface_port conduit_end reg_blk_size reg_blk_size Input 16
add_interface_port conduit_end rd_start rd_start Input 1
add_interface_port conduit_end data_out data_out Output 16
add_interface_port conduit_end blk_dma_end blk_dma_end Output 1
add_interface_port conduit_end reg_fifo_stat reg_fifo_stat Output 16


# 
# connection point read_master
# 
add_interface read_master avalon start
set_interface_property read_master addressUnits SYMBOLS
set_interface_property read_master associatedClock avm_clk
set_interface_property read_master associatedReset avm_reset
set_interface_property read_master bitsPerSymbol 8
set_interface_property read_master burstOnBurstBoundariesOnly false
set_interface_property read_master burstcountUnits WORDS
set_interface_property read_master doStreamReads false
set_interface_property read_master doStreamWrites false
set_interface_property read_master holdTime 0
set_interface_property read_master linewrapBursts false
set_interface_property read_master maximumPendingReadTransactions 0
set_interface_property read_master readLatency 0
set_interface_property read_master readWaitTime 1
set_interface_property read_master setupTime 0
set_interface_property read_master timingUnits Cycles
set_interface_property read_master writeWaitTime 0
set_interface_property read_master ENABLED true
set_interface_property read_master EXPORT_OF ""
set_interface_property read_master PORT_NAME_MAP ""
set_interface_property read_master CMSIS_SVD_VARIABLES ""
set_interface_property read_master SVD_ADDRESS_GROUP ""

add_interface_port read_master avm_addr address Output 32
add_interface_port read_master avm_rd read Output 1
add_interface_port read_master avm_rdvalid readdatavalid Input 1
add_interface_port read_master avm_rdata readdata Input 16
add_interface_port read_master avm_wait waitrequest Input 1


# 
# connection point avm_clk
# 
add_interface avm_clk clock end
set_interface_property avm_clk clockRate 0
set_interface_property avm_clk ENABLED true
set_interface_property avm_clk EXPORT_OF ""
set_interface_property avm_clk PORT_NAME_MAP ""
set_interface_property avm_clk CMSIS_SVD_VARIABLES ""
set_interface_property avm_clk SVD_ADDRESS_GROUP ""

add_interface_port avm_clk avm_clk clk Input 1


# 
# connection point avm_reset
# 
add_interface avm_reset reset end
set_interface_property avm_reset associatedClock avm_clk
set_interface_property avm_reset synchronousEdges DEASSERT
set_interface_property avm_reset ENABLED true
set_interface_property avm_reset EXPORT_OF ""
set_interface_property avm_reset PORT_NAME_MAP ""
set_interface_property avm_reset CMSIS_SVD_VARIABLES ""
set_interface_property avm_reset SVD_ADDRESS_GROUP ""

add_interface_port avm_reset avm_reset reset Input 1

